### ISSUE TITLE
Cannot create /var/snapd socket on Fedora 24 with SELinux enabled

### ISSUE THREAD

**Issue by zyga** [zyga/snapcore-fedora#1]
We currently have to disable SELinux to let snapd run. We should investigate how to lift this restriction.

**Comment by zyga** [comment]
This reddit post has useful details that would let us use seliux on fedora: 
https://www.reddit.com/r/linux/comments/4o2f8f/universal_snap_packages_launch_on_multiple_linux/d4cwijz

**Comment by Conan-Kudo** [comment]
I've started writing a basic policy module for snapd here: https://gitlab.com/Conan_Kudo/snapcore-selinux

**Comment by zyga** [comment]
This is now fixed. Stay tuned to use it in F25 using the upcoming snapd 2.23 release
