### ISSUE TITLE
[Request] Fedora 25 Support

### ISSUE THREAD

**Issue by petersaints** [zyga/snapcore-fedora#12]
There are no packages available for Fedora 25 at https://copr.fedorainfracloud.org/coprs/zyga/snapcore/. And the ones available for Fedora 23 and 24 are a bit out of date.

**Comment by zyga** [comment]
That's correct, due to the way how selinux is applied to all services managed by systemd I cannot get it to work without writing an extensive new selinux policy.

**Comment by petersaints** [comment]
But we could always set SELinux in the meantime if we really want/need Snap packages working on Fedora 25. Am I right?

**Comment by zyga** [comment]
We're preparing to release snapd 2.23 upstream and it should be released into Fedora 25. Stay tuned (we may do 2.23.1 on Monday/Tuesday if there are some extra fixes necessary).

**Comment by zyga** [comment]
I'm closing this bug as the repository should be retired now.

Please report further bugs on the Fedora package using the Fedora bug tracker: https://apps.fedoraproject.org/packages/snapd/bugs
