### ISSUE TITLE
snap cannot connect to the store on Fedora 23

### ISSUE THREAD

**Issue by Conan-Kudo** [zyga/snapcore-fedora#5]
When attempting to use `snap find`, `snap refresh`, `snap install`, or any other command that requires interacting with the store API on Fedora 23 Workstation, it bombs out with some variation of this error:

```
error: cannot list snaps: net/http: Client Transport of type *store.LoggedTransport doesn't support CancelRequest; Timeout not supported
```

**Comment by zyga** [comment]
Looks like something that's not captured at build time but should be.

**Comment by zyga** [comment]
This won't be fixed anymore as F23 is EOL
